server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      cors-configurations:
        '[/**]':
          allowedOrigins: "*"
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowedHeaders: "*"
          exposedHeaders:
            - Authorization
            - X-API-KEY
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/auth/**

        - id: product-service
          uri: ${PRODUCT_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/products/**, /products/**

        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/orders/**, /api/v1/orders/**

        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/payments/**

        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL:http://localhost:8085}
          predicates:
            - Path=/api/notifications/**

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

api-keys:
  product-service: PRODUCT-SERVICE-SECRET-KEY
  order-service: order-secret-key-123
  payment-service: payment-secret-key-123
  notification-service: notification-secret-key-123
