server.port=8083
spring.application.name=payment-service

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://admin:adminpassword@localhost:27020/payment_db?authSource=admin}
spring.data.mongodb.auto-index-creation=true

# OpenAPI / Swagger Config
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

