server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://admin:adminpassword@localhost:27019/order_db?authSource=admin}
      auto-index-creation: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

webhook:
  secret: ${WEBHOOK_SECRET:soc-payment-webhook-secret-key-2026}

logging:
  level:
    root: INFO
    com.ecommerce.orderservice: DEBUG
    org.springframework.data.mongodb: DEBUG
